### ISSUE TITLE
Updating to greater than 1.4.6, my app stops bundling

### ISSUE THREAD

**Issue by jacargentina** [react-native-community/react-native-cli#267] opened 2019-03-25 11:25 UTC
## Environment

```
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 1.57 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.11.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.5 => 16.8.5 
      react-native: ^0.59.1 => 0.59.1 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
```

## Description

When upgrading from 1.4.6 to a greather version (1.5.0 or 1.5.1) my app stops bundling. When i downgrade to 1.4.6 it just works fine again. 

## Reproducible Demo

1. git clone https://github.com/jacargentina/iResucito
2. cd iResucito
3. npm install; npm install @react-native-community/cli
4. react-natie run-ios

**Comment by thymikee** [comment] 2019-03-25 11:37
I cannot reproduce this, I can build and run your app just fine. One culprit – I removed `@react-native-community/cli` from deps and I'm using Yarn to install packages.

Looks like the issue is that you're installing `@react-native-community/cli` directly, while you shouldn't (it's a transitive dep of `react-native`). Remove it from package.json and from lockfile, install again. Should work.

Closing.

**Closed by thymikee** 2019-03-25 11:37 UTC
Labels: bug

**Comment by jacargentina** [comment] 2019-03-25 12:38
@thymikee  did this:
1. rm -rf node_modules
2. removed dep you pointed from package.json
3. removed package-lock.json
4. npm install
5. react-native run-ios

Sadly for me, it's not working. I must stay in 1.4.6 😔

<img width="1431" alt="Captura de pantalla 2019-03-25 a la(s) 09 36 19" src="https://user-images.githubusercontent.com/517228/54920317-b2730000-4ee1-11e9-991f-5e07959fcc20.png">

**Note**: this is from other app, but same result as in iResucito app

**Comment by jacargentina** [comment] 2019-03-25 13:05
@thymikee i've found this:

1. in a new terminal, run `react-native start` manually
2. in other terminal, run `react-native run-ios`

then it works. 🤔

**Comment by jacargentina** [comment] 2019-03-25 13:33
@thymikee I've just looked to git logs searching for something suspecting, and found that commit 88d7459695e62a5a226e70b2caf9bfadf0311f2a seems to remove an `await` when loading metro config.

Then i've cloned the repo, and built it on previous commit (which is c6d46b30d2adfd2ca7157fa8401f1cbcb2fea2cf), and copied to my project `node_modules/@react-native-community/cli`

Then `react-native run-ios` and guess what, it works!!!

**Comment by jacargentina** [comment] 2019-03-26 13:16
@thymikee Any chance to help me with this? Last comment about that missing `await` .... ?

**Comment by thymikee** [comment] 2019-03-26 13:21
This diff shouldn't change anything, because that function is returning a promise, and we await it in every place it's used.

As already said, I couldn't reproduce the issue in your app (I even use the very same Xcode version). Maybe there's something else about your setup that makes it unique?
