### ISSUE TITLE
react-native link fails copying assets

### ISSUE THREAD

**Issue by voxspox** [react-native-community/react-native-cli#233] opened 2019-03-14 10:31 UTC
## Environment

    React Native Environment Info:
      System:
        OS: Linux 4.15 ...
        Shell: 4.4.19 - /bin/bash
      Binaries:
        Node: 8.15.1 - /usr/bin/node
        npm: 6.9.0 - ~/bin/npm
      ...
      npmPackages:
        react: 16.6.3 => 16.6.3 
        react-native: 0.58.6 => 0.58.6 
      npmGlobalPackages:
        create-react-native-app: 2.0.2
        react-native-git-upgrade: 0.2.7

## Description

    $ react-native link
    ...
    error Something went wrong while linking. Error: ENOENT: no such file or directory, copyfile '...projectname/assets/fonts/MyFont.ttf' -> '...projectname/android/app/src/main/assets/fonts/MyFont.ttf' 

I think the problem is that the target folder is not existing. If I create it the error message disappears.

**Comment by thymikee** [comment] 2019-03-14 10:41
Duplicate of https://github.com/react-native-community/react-native-cli/issues/228. Fix landed on master and we'll release it shortly (you'll have to re-install `react-native` to make CLI update)

**Closed by thymikee** 2019-03-14 10:41 UTC
Labels: bug
