### ISSUE TITLE
Unable to set build path when executing run-ios

### ISSUE THREAD

**Issue by solkaz** [react-native-community/react-native-cli#269] opened 2019-03-25 21:32 UTC
## Environment

```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 283.70 MB / 16.00 GB
      Shell: 5.7.1 - /usr/local/bin/zsh
    Binaries:
      Node: 8.15.0 - /var/folders/z8/vcctz6491nz5t76b6py0gfd9x3djlb/T/yarn--1553548420908-0.23067134154145785/node
      Yarn: 1.15.2 - /var/folders/z8/vcctz6491nz5t76b6py0gfd9x3djlb/T/yarn--1553548420908-0.23067134154145785/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.1 => 0.59.1
```

## Description

I am upgrading a project from React-Native 0.58.6 to 0.59.1, and am encountering issues with _launching_ the iOS (using the CLI) after it has been built. I am able to build/install using XCode. We are building our app to something like `ios/build/Build` (which seemed to be a default at one point?), but after upgrading, `run-ios` expects the app to be located at `ios/build/$ACTIVE_SCHEME/Build`. I've not been able to find when the CLI's behavior changed (i.e. that it tries to install from a different path than before), so it's frustrating to have to debug this and realize that I have no way to override the CLI's behavior. 

This might be related to #143

**Comment by thymikee** [comment] 2019-03-25 21:36
Would you be able to provide a minimal repro so we can investigate?

**Comment by solkaz** [comment] 2019-03-25 21:36
Sure, I'll need some time since I don't have an OSS project off-hand with this issue.

**Comment by thymikee** [comment] 2019-03-25 21:37
Take all the time you need!

**Comment by solkaz** [comment] 2019-03-25 21:58
Thanks, created a repo [here](https://github.com/solkaz/rn-cli-build-path) that's a standard RN template generated with `react-native init MyApp`.

**Comment by thymikee** [comment] 2019-03-25 22:16
I actually cannot repro. Building both through Xcode _and_ `run-ios` works (builds, launches app, app displays welcome screen)

FYI this is the diff that introduced the new building path (it was a fix to an existing issue): https://github.com/react-native-community/react-native-cli/pull/128

**Comment by solkaz** [comment] 2019-03-25 22:44
I also was unable to reproduce using that repo on my personal machine, so I'm suspecting the global settings for XCode on my work machine. Unfortunately I cannot build the project in question on my personal machine.

**Comment by thymikee** [comment] 2019-03-25 22:47
I'll close the issue (because it's not a bug), but please feel free to post your findings, in case anyone else have similar problem.

**Closed by thymikee** 2019-03-25 22:47 UTC
Labels: bug
